/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author dell
 */
public class frmDuAn extends javax.swing.JFrame {

    private ListDuAn qlda = new ListDuAn();
    private ListDuAn qldaSearch = new ListDuAn();
    private int pos = 0;

    /**
     * Creates new form frmDuAn
     */
    public frmDuAn() {
        qlda = new ListDuAn(qlda.readDuAn("DuAn.txt"));
        initComponents();
        hienThi();
        btnSuaDuAn.setEnabled(false);
        btnXoaDuAn.setEnabled(false);
        btnHuyDuAn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbDuAn = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenDuAn = new javax.swing.JTextField();
        btnThemDuAn = new javax.swing.JButton();
        btnXoaDuAn = new javax.swing.JButton();
        btnSuaDuAn = new javax.swing.JButton();
        btnLuuDuAn = new javax.swing.JButton();
        btnHuyDuAn = new javax.swing.JButton();
        btnTroveDuAn = new javax.swing.JButton();
        txtSearchMa = new javax.swing.JTextField();
        txtSoNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtSearchTen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboSort = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbDuAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Dự Án", "Tên Dự Án", "Số Nhân Viên tối đa"
            }
        ));
        tbDuAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDuAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDuAn);

        jLabel1.setText("Mã Dự Án Sẽ được chọn mặc định");

        jLabel2.setText("Tên Dự Án");

        btnThemDuAn.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_sign-add_299068.png")); // NOI18N
        btnThemDuAn.setText("Thêm");
        btnThemDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDuAnActionPerformed(evt);
            }
        });

        btnXoaDuAn.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_sign-add_299068.png")); // NOI18N
        btnXoaDuAn.setText("Xóa");
        btnXoaDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDuAnActionPerformed(evt);
            }
        });

        btnSuaDuAn.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_Folder_folder_up_folder_upload_update_folder_upload_1886931.png")); // NOI18N
        btnSuaDuAn.setText("Sửa");
        btnSuaDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDuAnActionPerformed(evt);
            }
        });

        btnLuuDuAn.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_Save_70652.png")); // NOI18N
        btnLuuDuAn.setText("Lưu");
        btnLuuDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuDuAnActionPerformed(evt);
            }
        });

        btnHuyDuAn.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_error_1646012.png")); // NOI18N
        btnHuyDuAn.setText("Hủy");
        btnHuyDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDuAnActionPerformed(evt);
            }
        });

        btnTroveDuAn.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_39_Exit_Arrow_Door_Signout_Out_Close_2142693.png")); // NOI18N
        btnTroveDuAn.setText("Trở về");
        btnTroveDuAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroveDuAnActionPerformed(evt);
            }
        });

        txtSearchMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchMaActionPerformed(evt);
            }
        });
        txtSearchMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchMaKeyReleased(evt);
            }
        });

        txtSoNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNVActionPerformed(evt);
            }
        });
        txtSoNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoNVKeyTyped(evt);
            }
        });

        jLabel3.setText("Số Nhân Viên tối đa");

        jLabel12.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_Search_icon_2541673.png")); // NOI18N
        jLabel12.setText("Tìm Kiếm Theo Mã Dự Án");

        txtSearchTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTenActionPerformed(evt);
            }
        });
        txtSearchTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchTenKeyReleased(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_Search_icon_2541673.png")); // NOI18N
        jLabel13.setText("Tìm Kiếm Theo Tên Dự Án");
        jLabel13.setToolTipText("");

        jLabel14.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_arrows-22_808395.png")); // NOI18N
        jLabel14.setText("Sắp xếp");

        cboSort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Tên Dự Án", "Số Nhân Viên" }));
        cboSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSortActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 0, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DỰ ÁN");

        jLabel5.setText("Danh sách Dự Án");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnThemDuAn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                                .addComponent(btnXoaDuAn)
                                                .addGap(44, 44, 44)
                                                .addComponent(btnSuaDuAn)
                                                .addGap(73, 73, 73)
                                                .addComponent(btnLuuDuAn)
                                                .addGap(74, 74, 74)
                                                .addComponent(btnHuyDuAn)
                                                .addGap(46, 46, 46))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel14)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboSort, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTroveDuAn)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(23, 23, 23)
                                        .addComponent(txtSearchMa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSearchTen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenDuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtSearchMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSoNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearchTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addComponent(btnThemDuAn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTroveDuAn)
                            .addComponent(btnHuyDuAn)
                            .addComponent(btnLuuDuAn)
                            .addComponent(btnSuaDuAn)
                            .addComponent(btnXoaDuAn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tbDuAn.getModel();

        model.setRowCount(0);
        for (DuAn nv : qlda.getList()) {
            model.addRow(new Object[]{nv.getMaDuAn(), nv.getTenDuAn(), nv.getSoNV()});

        }
    }

    public DuAn khoiTao() {

        String sTen = txtTenDuAn.getText();
        int sSoNV = Integer.parseInt(this.txtSoNV.getText());
        int ma = 1000;
        for (DuAn nv : qlda.getList()) {
            ma++;
        }
        DuAn da = new DuAn(ma, sTen, sSoNV);
        return da;
    }

    public void showAllRows(ListDuAn qlda) {
        DefaultTableModel model = (DefaultTableModel) tbDuAn.getModel();

        model.setRowCount(0);
        for (DuAn nv : qlda.getList()) {
            model.addRow(new Object[]{nv.getMaDuAn(), nv.getTenDuAn()});

        }
    }

    public void clearAllRows() {
        DefaultTableModel model = (DefaultTableModel) tbDuAn.getModel();
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
    }

    public boolean isNumber(String s) {
        if (s.length() == 0) {
            return false;
        }
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return false;
            }
        }
        return true;
    }
    private void btnThemDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDuAnActionPerformed
        // TODO add your handling code here:
        if (txtTenDuAn.getText().length() != 0 && txtSoNV.getText().length() != 0) {
            qlda.insertDA(khoiTao());
            JOptionPane.showMessageDialog(rootPane, "Thêm Thành Công!");
            hienThi();
            clearField();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nhap day du thong tin!");
        }
    }//GEN-LAST:event_btnThemDuAnActionPerformed
    public void clearField() {
        txtTenDuAn.setText("");
        txtSoNV.setText("");

    }
    private void btnXoaDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDuAnActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Ban co muon xoa khong") == 0) {
            clearAllRows();
            qlda.deleteDuAnByViTri(pos);
            hienThi();
        }
    }//GEN-LAST:event_btnXoaDuAnActionPerformed

    private void btnSuaDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDuAnActionPerformed
//        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel) tbDuAn.getModel();
//       
//           model.setValueAt(txtTenDuAn.getText(),tbDuAn.getSelectedRow(),1);
//       JOptionPane.showMessageDialog(rootPane, "Thông tin đã được cập nhật!");
        int ma = qlda.getDuAnAt(pos).getMaDuAn();
        String sTen = this.txtTenDuAn.getText();
        int nSoNV = Integer.parseInt(this.txtSoNV.getText());
        DuAn da = new DuAn(ma, sTen, nSoNV);

        qlda = new ListDuAn(qlda.editDuAn(ma, da));
        clearAllRows();
        hienThi();
    }//GEN-LAST:event_btnSuaDuAnActionPerformed

    private void tbDuAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDuAnMouseClicked
        // TODO add your handling code here:
        pos = tbDuAn.getSelectedRow();
        btnXoaDuAn.setEnabled(true);
        btnHuyDuAn.setEnabled(true);
        btnSuaDuAn.setEnabled(true);
//        btnXoaDuAn.setEnabled(true);
        btnThemDuAn.setEnabled(false);
        int row = tbDuAn.getSelectedRow();
        txtTenDuAn.setText(qlda.getList().get(row).getTenDuAn());
    }//GEN-LAST:event_tbDuAnMouseClicked

    private void txtSearchMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMaActionPerformed

    private void txtSearchMaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchMaKeyReleased
//        // TODO add your handling code here:
//        DefaultTableModel table = (DefaultTableModel)tbDuAn.getModel();
//        String search = txtSearchMa.getText().toLowerCase();
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
//        tbDuAn.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter(search));
        clearAllRows();
        String search = txtSearchMa.getText();
        if (search.equals("")) {
            hienThi();
        }
        if (!isNumber(search)) {
            return;
        }
        qldaSearch = new ListDuAn(qlda.timKiemTheoMa(Integer.parseInt(search)));
        showAllRows(qldaSearch);
    }//GEN-LAST:event_txtSearchMaKeyReleased

    private void txtSearchTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTenActionPerformed

    private void txtSearchTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchTenKeyReleased
        clearAllRows();
        String search = txtSearchTen.getText();
        if (search.equals("")) {
            hienThi();
            return;
        }
        qldaSearch = new ListDuAn(qlda.timKiemTheoTen(search));
        showAllRows(qldaSearch);
    }//GEN-LAST:event_txtSearchTenKeyReleased

    private void btnLuuDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuDuAnActionPerformed
        if (qlda.writeDuAn("DuAn.txt") && qlda.writeTenDuAn("TenDuAn.txt")) {
            JOptionPane.showMessageDialog(rootPane, "Đã lưu danh sách xuống file!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi trong quá trình lưu file!");
        }
    }//GEN-LAST:event_btnLuuDuAnActionPerformed

    private void cboSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSortActionPerformed
        int index = cboSort.getSelectedIndex();
        clearAllRows();
        switch (index) {
            case 0:
                //Do something please ><
                break;
            case 1:
                qlda = new ListDuAn(qlda.sortTheoTen());
                break;
            case 2:
                qlda = new ListDuAn(qlda.sortTheoSoNV());
                break;
        }
        hienThi();
    }//GEN-LAST:event_cboSortActionPerformed

    private void btnHuyDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDuAnActionPerformed
        // TODO add your handling code here:
        btnThemDuAn.setEnabled(true);
        btnXoaDuAn.setEnabled(false);
        btnSuaDuAn.setEnabled(false);
        btnHuyDuAn.setEnabled(false);
    }//GEN-LAST:event_btnHuyDuAnActionPerformed

    private void btnTroveDuAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroveDuAnActionPerformed
        // TODO add your handling code here:
        frmTrangChu frm = new frmTrangChu();
        frm.setVisible(true);
    }//GEN-LAST:event_btnTroveDuAnActionPerformed

    private void txtSoNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNVActionPerformed

    private void txtSoNVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoNVKeyTyped
        // TODO add your handling code here:
        String tuoi = txtSoNV.getText();
        int length = tuoi.length();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length < 10) {
                txtSoNV.setEditable(true);
            } else {
                txtSoNV.setEditable(false);
            }
        } else {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtSoNVKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDuAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDuAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyDuAn;
    private javax.swing.JButton btnLuuDuAn;
    private javax.swing.JButton btnSuaDuAn;
    private javax.swing.JButton btnThemDuAn;
    private javax.swing.JButton btnTroveDuAn;
    private javax.swing.JButton btnXoaDuAn;
    private javax.swing.JComboBox cboSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDuAn;
    private javax.swing.JTextField txtSearchMa;
    private javax.swing.JTextField txtSearchTen;
    private javax.swing.JTextField txtSoNV;
    private javax.swing.JTextField txtTenDuAn;
    // End of variables declaration//GEN-END:variables
}
