/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import static com.sun.java.accessibility.util.AWTEventMonitor.addActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author dell
 */
public class frmNhanVien extends javax.swing.JFrame {

    private ListNhanVien qlnv = new ListNhanVien();
    private ListNhanVien qlnvSearch = new ListNhanVien();
    private ArrayList<NhanVien> listNV;

    private int pos = 0;

    /**
     * Creates new form frmNhanVien
     */
    public frmNhanVien() {

        qlnv = new ListNhanVien(qlnv.readNhanVien("NhanVien.txt"));
        initComponents();
        init();
        initDuAn();
        hienThi();
        btnSuaNV.setEnabled(false);
        btnXoaNV.setEnabled(false);
        btnHuyNV.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtSearchNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbGioitinh = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbChucVu = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbDuan = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnXoaNV = new javax.swing.JButton();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        txtDiachi = new javax.swing.JTextField();
        btnLuuNV = new javax.swing.JButton();
        btnHuyNV = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnTrove = new javax.swing.JButton();
        txtTenNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTuoi = new javax.swing.JTextField();
        cbPhongban = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbMess = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSearchMa = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        cboSort = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSearchNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNVActionPerformed(evt);
            }
        });
        txtSearchNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNVKeyReleased(evt);
            }
        });

        jLabel4.setText("Tên Nhân Viên:");

        jLabel5.setText("Giới tính:");

        cbGioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));
        cbGioitinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGioitinhItemStateChanged(evt);
            }
        });

        jLabel8.setText("Chức vụ:");

        jLabel6.setText("Tuổi:");

        cbChucVu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhân viên", "Tạp vụ", " " }));

        jLabel7.setText("Phòng ban:");

        jLabel9.setText("Dự án:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NHÂN VIÊN");

        btnXoaNV.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_sign-add_299068.png")); // NOI18N
        btnXoaNV.setText("Xóa");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        btnThemNV.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_sign-add_299068.png")); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnSuaNV.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_Folder_folder_up_folder_upload_update_folder_upload_1886931.png")); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.setToolTipText("");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });

        btnLuuNV.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_Save_70652.png")); // NOI18N
        btnLuuNV.setText("Lưu");
        btnLuuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuNVActionPerformed(evt);
            }
        });

        btnHuyNV.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_error_1646012.png")); // NOI18N
        btnHuyNV.setText("Hủy");
        btnHuyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyNVActionPerformed(evt);
            }
        });

        jLabel3.setText("Địa chỉ:");

        btnTrove.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_39_Exit_Arrow_Door_Signout_Out_Close_2142693.png")); // NOI18N
        btnTrove.setText("Trở về");
        btnTrove.setToolTipText("");
        btnTrove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroveActionPerformed(evt);
            }
        });

        jLabel10.setText("Danh Sách Nhân Viên");

        txtTuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTuoiActionPerformed(evt);
            }
        });
        txtTuoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTuoiKeyTyped(evt);
            }
        });

        cbPhongban.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Giới tính", "Tuổi", "Địa chỉ", "Phòng ban", "Chức vụ", "Dự án"
            }
        ));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        jLabel2.setText("Mã Nhân Viên Sẽ Được Chọn Từ Hệ Thống");

        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_Search_icon_2541673.png")); // NOI18N
        jLabel11.setText("Tìm Kiếm");
        jLabel11.setToolTipText("");

        txtSearchMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchMaActionPerformed(evt);
            }
        });
        txtSearchMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchMaKeyReleased(evt);
            }
        });

        jTextField2.setText("Mã");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField3.setText("Tên");

        cboSort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Tuổi Nhân Viên", "Tên Nhân Viên" }));
        cboSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSortActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("F:\\Java\\Project\\src\\project\\icon\\iconfinder_arrows-22_808395.png")); // NOI18N
        jLabel12.setText("Sắp xếp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemNV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(btnXoaNV)
                                .addGap(115, 115, 115))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnSuaNV)
                                            .addComponent(jLabel1))
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPhongban, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSearchMa)
                                            .addComponent(txtSearchNV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel11)))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLuuNV)
                                .addGap(114, 114, 114)
                                .addComponent(btnHuyNV)
                                .addGap(88, 88, 88)
                                .addComponent(btnTrove)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbMess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cboSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSearchMa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSearchNV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cbPhongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(cbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cbDuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTrove)
                            .addComponent(btnHuyNV)
                            .addComponent(btnLuuNV)
                            .addComponent(btnSuaNV)
                            .addComponent(btnXoaNV)
                            .addComponent(btnThemNV))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMess))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGioitinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGioitinhItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGioitinhItemStateChanged

    public void loadPhongBan() {

    }

    public void clearAllRows() {
        DefaultTableModel model = (DefaultTableModel) tbNhanVien.getModel();
        if (model.getRowCount() > 0) {
            for (int i = model.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
    }

    public void init() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        String fileName = ("F://Java//Project//TenPhong.txt");
        File file = new File(fileName);
        try (Scanner in = new Scanner(file)) {
            while (in.hasNextLine()) {
                String line;
                line = in.nextLine();
                model.addElement(line);
                cbPhongban.setModel(model);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("File can not found");
        }
    }

    public void initDuAn() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        String fileName = ("F://Java//Project//TenDuAn.txt");
        File file = new File(fileName);
        try (Scanner in = new Scanner(file)) {
            while (in.hasNextLine()) {
                String line;
                line = in.nextLine();
                model.addElement(line);
                cbDuan.setModel(model);
            }
        } catch (FileNotFoundException ex) {
            System.out.println("File can not found");
        }
    }

    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tbNhanVien.getModel();
        model.setRowCount(0);
        for (NhanVien nv : qlnv.getList()) {
            model.addRow(new Object[]{nv.getMaNV(), nv.getTenNV(), nv.getGioiTinh(), nv.getTuoi(), nv.getDiaChi(), nv.getPhongBan(), nv.getChucVu(), nv.getDuAn()});

        }
    }

    public void showAllRows(ListNhanVien qlnv) {
        DefaultTableModel model = (DefaultTableModel) tbNhanVien.getModel();
        model.setRowCount(0);
        for (NhanVien nv : qlnv.getList()) {
            model.addRow(new Object[]{nv.getMaNV(), nv.getTenNV(), nv.getGioiTinh(), nv.getTuoi(), nv.getDiaChi(), nv.getPhongBan(), nv.getChucVu(), nv.getDuAn()});

        }
    }

    public NhanVien khoiTao() {

        String sTen = txtTenNV.getText();
        String sGioitinh = cbGioitinh.getSelectedItem().toString();
        int nTuoi = Integer.parseInt(txtTuoi.getText());
        int ma = 10000;
        for (NhanVien nv : qlnv.getList()) {
            ma++;

        }
        String sDiachi = txtDiachi.getText();
        String sPhongban = cbPhongban.getSelectedItem().toString();
        String sChucvu = cbChucVu.getSelectedItem().toString();
        String sDuan = cbDuan.getSelectedItem().toString();
        NhanVien nv = new NhanVien(sTen, sGioitinh, nTuoi, ma, sDiachi, sPhongban, sChucvu, sDuan);
        return nv;
    }
    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        int pos = tbNhanVien.getSelectedRow();
        if (JOptionPane.showConfirmDialog(null, "Ban co muon xoa khong") == 0) {
            qlnv.deleteNhanVien(pos);
            clearAllRows();
            hienThi();
        }


    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        if (txtTenNV.getText().length() != 0 && txtTuoi.getText().length() != 0 && txtDiachi.getText().length() != 0) {
            qlnv.insertNV(khoiTao());
            JOptionPane.showMessageDialog(rootPane, "Thêm Thành Công!");
            hienThi();
            clearField();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nhap day du thong tin!");
        }


    }//GEN-LAST:event_btnThemNVActionPerformed
    public void clearField() {
        txtTenNV.setText("");
        txtTuoi.setText("");
        txtDiachi.setText("");
    }
    private void btnHuyNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyNVActionPerformed
        // TODO add your handling code here:
        btnThemNV.setEnabled(true);
        btnXoaNV.setEnabled(false);
        btnSuaNV.setEnabled(false);
        btnHuyNV.setEnabled(false);
        clearField();
    }//GEN-LAST:event_btnHuyNVActionPerformed

    private void txtTuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTuoiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTuoiActionPerformed

    private void txtTuoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTuoiKeyTyped
        // TODO add your handling code here:
        String tuoi = txtTuoi.getText();
        int length = tuoi.length();
        char c = evt.getKeyChar();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length < 3) {
                txtTuoi.setEditable(true);
            } else {
                txtTuoi.setEditable(false);
            }
        } else {
            if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
                getToolkit().beep();
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtTuoiKeyTyped

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        // TODO add your handling code here:
        if (tbNhanVien.getRowCount() != 0) {
            pos = tbNhanVien.getSelectedRow();
        }
        btnHuyNV.setEnabled(true);
        btnSuaNV.setEnabled(true);
        btnXoaNV.setEnabled(true);
        btnThemNV.setEnabled(false);
        int row = tbNhanVien.getSelectedRow();
        txtTenNV.setText(qlnv.getList().get(row).getTenNV());
        cbGioitinh.setSelectedItem(qlnv.getList().get(row).getGioiTinh());
        txtTuoi.setText(String.valueOf(qlnv.getList().get(row).getTuoi()));
        txtDiachi.setText(qlnv.getList().get(row).getDiaChi());
        cbPhongban.setSelectedItem(qlnv.getList().get(row).getPhongBan());
        cbChucVu.setSelectedItem(qlnv.getList().get(row).getChucVu());
        cbDuan.setSelectedItem(qlnv.getList().get(row).getDuAn());
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        // TODO add your handling code here:
        int ma = qlnv.getNhanVienAt(pos).getMaNV();
        String sTen = txtTenNV.getText();
        String sGioitinh = cbGioitinh.getSelectedItem().toString();
        int nTuoi = Integer.parseInt(txtTuoi.getText());
        String sDiachi = txtDiachi.getText();
        String sPhongban = cbPhongban.getSelectedItem().toString();
        String sChucvu = cbChucVu.getSelectedItem().toString();
        String sDuan = cbDuan.getSelectedItem().toString();
        NhanVien nv = new NhanVien(sTen, sGioitinh, nTuoi, ma, sDiachi, sPhongban, sChucvu, sDuan);

        qlnv = new ListNhanVien(qlnv.editNhanVien(ma, nv));
        clearAllRows();
        hienThi();

    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnLuuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuNVActionPerformed
        // TODO add your handling code here:
        if (qlnv.writeNhanVien("NhanVien.txt")) {
            JOptionPane.showMessageDialog(rootPane, "Đã lưu danh sách xuống file!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi trong quá trình lưu file!");
        }
    }//GEN-LAST:event_btnLuuNVActionPerformed

    private void txtSearchNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNVKeyReleased
        // TODO add your handling code here:
//       DefaultTableModel table = (DefaultTableModel)tbNhanVien.getModel();
//       String search = txtSearchNV.getText().toLowerCase();
//       TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
//       tbNhanVien.setRowSorter(tr);
//       tr.setRowFilter(RowFilter.regexFilter(search));
        clearAllRows();
        String search = txtSearchNV.getText();
        if (search.equals("")) {
            hienThi();
            return;
        }

        qlnvSearch = new ListNhanVien(qlnv.timKiemTheoTen(search));
        showAllRows(qlnvSearch);


    }//GEN-LAST:event_txtSearchNVKeyReleased
    public boolean isNumber(String s) {
        if (s.length() == 0) {
            return false;
        }
        for (int i = 0; i < s.length(); i++) {
            if (!Character.isDigit(s.charAt(i))) {
                return false;
            }
        }
        return true;
    }
    private void txtSearchMaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchMaKeyReleased
        clearAllRows();
        String search = txtSearchMa.getText();
        if (search.equals("")) {
            hienThi();
        }
        if (!isNumber(search)) {
            return;
        }
        qlnvSearch = new ListNhanVien(qlnv.timKiemTheoMa(Integer.parseInt(search)));
        showAllRows(qlnvSearch);
    }//GEN-LAST:event_txtSearchMaKeyReleased

    private void cboSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSortActionPerformed
        int index = cboSort.getSelectedIndex();
        clearAllRows();
        switch (index) {
            case 0:
                //Do something please ><
                break;
            case 1:
                qlnv = new ListNhanVien(qlnv.sortTheoTuoi());
                break;
            case 2:
                qlnv = new ListNhanVien(qlnv.sortTheoTen());
                break;
        }
        hienThi();
    }//GEN-LAST:event_cboSortActionPerformed

    private void txtSearchNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNVActionPerformed

    private void btnTroveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroveActionPerformed
        // TODO add your handling code here:
        frmTrangChu frm = new frmTrangChu();
        frm.setVisible(true);
    }//GEN-LAST:event_btnTroveActionPerformed

    private void txtSearchMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyNV;
    private javax.swing.JButton btnLuuNV;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnTrove;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbChucVu;
    private javax.swing.JComboBox cbDuan;
    private javax.swing.JComboBox cbGioitinh;
    private javax.swing.JComboBox cbPhongban;
    private javax.swing.JComboBox cboSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbMess;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtSearchMa;
    private javax.swing.JTextField txtSearchNV;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables

}
